#ifndef TOKEN_H
#define TOKEN_H

#include <stddef.h>

#include "common.h"
#include "dd_string.h"

#define TOKENKINDS \
    TOKENKIND(TOKEN_INVALID, "INVALID"), \
    TOKENKIND(TOKEN_UNKNOWN, "UNKNOWN"), \
    TOKENKIND(TOKEN_EOF, "EOF"), \
    TOKENKIND(TOKEN_LEFT_PAREN, "("), \
    TOKENKIND(TOKEN_RIGHT_PAREN, ")"), \
    TOKENKIND(TOKEN_LEFT_BRACE, "{"), \
    TOKENKIND(TOKEN_RIGHT_BRACE, "}"), \
    TOKENKIND(TOKEN_SEMICOLON, ";"), \
\
    TOKENKIND(TOKEN_OPERATORS_BEGIN, ""), \
    TOKENKIND(TOKEN_OPERATORS_BINARY_BEGIN, ""), \
    TOKENKIND(TOKEN_OPERATORS_ASSIGN_BEGIN, ""), \
    TOKENKIND(TOKEN_OP_EQUAL, "="), \
    TOKENKIND(TOKEN_OP_PLUS_EQUAL, "+="), \
    TOKENKIND(TOKEN_OP_MINUS_EQUAL, "-="), \
    TOKENKIND(TOKEN_OP_ASTERISK_EQUAL, "*="), \
    TOKENKIND(TOKEN_OP_SLASH_EQUAL, "/="), \
    TOKENKIND(TOKEN_OP_PERCENT_EQUAL, "%="), \
    TOKENKIND(TOKEN_OP_AMPERSAND_EQUAL, "&="), \
    TOKENKIND(TOKEN_OP_BAR_EQUAL, "|="), \
    TOKENKIND(TOKEN_OP_CARET_EQUAL, "^="), \
    TOKENKIND(TOKEN_OP_LSHFT_EQUAL, "<<="), \
    TOKENKIND(TOKEN_OP_RSHFT_EQUAL, ">>="), \
    TOKENKIND(TOKEN_OPERATORS_ASSIGN_END, ""), \
    TOKENKIND(TOKEN_OP_ASTERISK, "*"), \
    TOKENKIND(TOKEN_OP_SLASH, "/"), \
    TOKENKIND(TOKEN_OP_PERCENT, "%"), \
    TOKENKIND(TOKEN_OP_DOUBLE_AMP, "&&"), \
    TOKENKIND(TOKEN_OP_DOUBLE_BAR, "||"), \
    TOKENKIND(TOKEN_OP_DOUBLE_EQUAL, "=="), \
    TOKENKIND(TOKEN_OP_EXCLAMATION_EQUAL, "!="), \
    TOKENKIND(TOKEN_OP_LT, "<"), \
    TOKENKIND(TOKEN_OP_GT, ">"), \
    TOKENKIND(TOKEN_OP_LTE, "<="), \
    TOKENKIND(TOKEN_OP_GTE, ">="), \
    TOKENKIND(TOKEN_OP_AMPERSAND, "&"), \
    TOKENKIND(TOKEN_OP_BAR, "|"), \
    TOKENKIND(TOKEN_OP_CARET, "^"), \
    TOKENKIND(TOKEN_OP_LSHFT, "<<"), \
    TOKENKIND(TOKEN_OP_RSHFT, ">>"), \
    TOKENKIND(TOKEN_OP_QUESTION, "?"), \
    TOKENKIND(TOKEN_OPERATORS_UNARY_BEGIN, ""), \
    TOKENKIND(TOKEN_OP_MINUS, "-"), \
    TOKENKIND(TOKEN_OP_PLUS, "+"), \
    TOKENKIND(TOKEN_OPERATORS_BINARY_END, ""), \
    TOKENKIND(TOKEN_OP_COMPLEMENT, "~"), \
    TOKENKIND(TOKEN_OP_EXCLAMATION, "!"), \
    TOKENKIND(TOKEN_OP_DECREMENT, "--"), \
    TOKENKIND(TOKEN_OP_INCREMENT, "++"), \
    TOKENKIND(TOKEN_OPERATORS_UNARY_END, ""), \
    TOKENKIND(TOKEN_OP_COLON, ":"), \
    TOKENKIND(TOKEN_OP_COMMA, ","), \
    TOKENKIND(TOKEN_OPERATORS_END, ""), \
\
    TOKENKIND(TOKEN_KEYWORDS_BEGIN, ""), \
    TOKENKIND(TOKEN_TYPE_SPECIFIERS_BEGIN, ""), \
    TOKENKIND(TOKEN_KW_INT, "int"), \
    TOKENKIND(TOKEN_KW_VOID, "void"), \
    TOKENKIND(TOKEN_TYPE_SPECIFIERS_END, ""), \
    TOKENKIND(TOKEN_STORAGE_CLASS_BEGIN, ""), \
    TOKENKIND(TOKEN_KW_STATIC, "static"), \
    TOKENKIND(TOKEN_KW_EXTERN, "extern"), \
    TOKENKIND(TOKEN_STORAGE_CLASS_END, ""), \
    TOKENKIND(TOKEN_KW_RETURN, "return"), \
    TOKENKIND(TOKEN_KW_IF, "if"), \
    TOKENKIND(TOKEN_KW_ELSE, "else"), \
    TOKENKIND(TOKEN_KW_GOTO, "goto"), \
    TOKENKIND(TOKEN_KW_DO, "do"), \
    TOKENKIND(TOKEN_KW_WHILE, "while"), \
    TOKENKIND(TOKEN_KW_FOR, "for"), \
    TOKENKIND(TOKEN_KW_BREAK, "break"), \
    TOKENKIND(TOKEN_KW_CONTINUE, "continue"), \
    TOKENKIND(TOKEN_KW_SWITCH, "switch"), \
    TOKENKIND(TOKEN_KW_CASE, "case"), \
    TOKENKIND(TOKEN_KW_DEFAULT, "default"), \
    TOKENKIND(TOKEN_KEYWORDS_END, ""), \
\
    TOKENKIND(TOKEN_IDENTIFIER, "identifier"), \
    TOKENKIND(TOKEN_CONSTANT, "constant"), \
    TOKENKIND(TOKENKIND_LEN, "")

typedef enum tokenkind_ {
#define TOKENKIND(tk, sl) tk
    TOKENKINDS
#undef TOKENKIND
} TokenKind;

static String token_literals[] = {
#define TOKENKIND(tk, sl) (String){ .cstr = (char *)sl, .len = sizeof(sl)-1 }
    TOKENKINDS
#undef TOKENKIND
};

typedef struct token_ {
    TokenKind kind;
    Position pos;
    const String *text;
} Token;

#define TOKENKIND_IS_OPERATOR(tk) \
    ((tk) > TOKEN_OPERATORS_BEGIN && (tk) < TOKEN_OPERATORS_END)

#define TOKENKIND_IS_BINARY_OPERATOR(tk) \
    ((tk) > TOKEN_OPERATORS_BINARY_BEGIN && (tk) < TOKEN_OPERATORS_BINARY_END)

#define TOKENKIND_IS_ASSIGNMENT(tk) \
    ((tk) > TOKEN_OPERATORS_ASSIGN_BEGIN && (tk) < TOKEN_OPERATORS_ASSIGN_END)

#define TOKENKIND_IS_KEYWORD(tk) \
    ((tk) > TOKEN_KEYWORDS_BEGIN && (tk) < TOKEN_KEYWORDS_END)

typedef struct tokenList_ {
    Token *toks;
    size_t len;
    size_t cap;
} TokenList;

void TokenList_init(TokenList *tl);
void TokenList_destroy(TokenList* tl);
void TokenList_append(TokenList* tl, Token tok);
void TokenList_print(TokenList *tl);

#endif // TOKEN_H
